### ISSUE TITLE
dataset

### ISSUE THREAD

**Issue by a310694487** [amiralansary/rl-medical#11]
Hello Amir,
Could you tell us how to make a dataset for automatic view planning? for your data set is not public.Thank you so much!

**Comment by amiralansary** [comment]
Hey,
You will find different plane samplers in [detectPlaneHelper.py](https://github.com/amiralansary/tensorpack-medical/blob/master/examples/AutomaticViewPlanning/DQN/detectPlaneHelper.py)
This plane sampler is used during the training and testing to sample any plane from a 3d image scan.

**Comment by a310694487** [comment]
yeah,
Thank you so much, and I wonder how to make a dataset for trainning and test from raw data.

**Comment by amiralansary** [comment]
It should be very similar to the detectPlaneHelper module. However, you may need to modify few functions if the dataset is different.
