### ISSUE TITLE
'function' object has no attribute 'symbolic_function'

### ISSUE THREAD

**Issue by Vonisoa** [amiralansary/rl-medical#12]
Hi, when I try to run the DQN.py inside `examples/LandmarkDetection` using the command:
`python DQN.py --task play --algo DQN --gpu 0 --load data/models/DQN_multiscale_brain_mri_point_pc_ROI_45_45_45/model-600000 --files './data/filenames/image_files.txt'`

I got the following error:

> File "DQN.py", line 88, in _get_DQN_prediction
>     with argscope(Conv3D, nl=PReLU.symbolic_function, use_bias=True):
> AttributeError: 'function' object has no attribute 'symbolic_function'

Can you help please?

**Comment by klekass** [comment]
I had the same error, because I was using the wrong tensorpack version. Downgrading tensorpack to version 0.9.5 solved the issue for me.

**Comment by amiralansary** [comment]
Hey @Vonisoa 
As @klekass mentioned, you will need to use the same package versions as here [requirments](https://github.com/amiralansary/rl-medical#dependencies)
