### ISSUE TITLE
Input data format

### ISSUE THREAD

**Issue by RegoResearch** [amiralansary/rl-medical#13]
Hello, I am Sky Kim.

I am fascinated in your project which finds mid-sagittal plane in 3d volume!
However, when I try to run this source code, I realized that your data is not public.
If I want to run this code with my own input data, how could I make data format and 'list_of_train_filenames.txt'?
Please let me know the sample format of the train and test data.
Thanks in advance.

**Comment by amiralansary** [comment]
Hey Sky Kim,

I am glad you have found our work inspiring. The data for the view planning example can be a bit tricky. You would need the list of the filenames for your training and testing, and there should be a corresponding list of the ground truth planes. In the mid-sagittal case, the plane can be extracted using standard anatomical landmarks. You may need to modify this part of the code to work with the data you will be running the code on.

Best, Amir
