### ISSUE TITLE
About the success ratio for Automatic View Planning

### ISSUE THREAD

**Issue by LeeKeyu** [amiralansary/rl-medical#18]
Dear Amir Alansary,

May I ask what success ratio did you achieve in training? Since after training for more than 48h (2,875,000 steps) I could only reach a success ratio of about 0.1 and the mean distance between plane params were more than 10. In your paper I noticed that you trained the model for 12-24 hours, so I really want to know about your success ratio in training. May I ask for your help?
Thank you very much.

Best,
Keyu

**Comment by amiralansary** [comment]
Hi Keyu,

The success ratio is defined as the ratio of cases that the distance between the predicted and target plane is less than specific value, e.g. 1mm. The increase of the success ratio with training is a sign that the model is learning. I suspect in your case the model has not learned for some reason. 

Best, Amir
