### ISSUE TITLE
about ADNI dataset

### ISSUE THREAD

**Issue by torressliu** [amiralansary/rl-medical#21]
After I applied for ADNI data set, I did not find the anatomical landmark labels of corresponding MRI. Could you please tell me whether the dataset you used for training was marked by yourself ? If not,could you tell me how to get the label datasets ?

**Comment by torressliu** [comment]
which tool do you use to label MRI image ?

**Comment by amiralansary** [comment]
Unfortunately, the landmarks were annotated by our medical collaborators from the hospital, and cannot be shared. 
There are several tools that can be used for annotating the images: [itksnap](http://www.itksnap.org/pmwiki/pmwiki.php), [MITK](https://www.mitk.org/wiki/The_Medical_Imaging_Interaction_Toolkit_(MITK)) and [MIRTK viewer](https://github.com/MIRTK/Viewer)
