### ISSUE TITLE
how can I get the cardiac dataset in this project?

### ISSUE THREAD

**Issue by hlyf-xs** [amiralansary/rl-medical#23]
hello. I'm really intersted in this project, but how can I get the cardiac dataset in this project? Can you give me a hand?

**Comment by amiralansary** [comment]
This is related to #22 
Unfortunately, the cardiac dataset used in this project is not publicly available. However, the code should be working on any other 3D medical data.

**Comment by hlyf-xs** [comment]
ohoh, I'm curious about how you get the dataset? Can you help me?




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "amiralansary/rl-medical"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年3月15日(星期一) 晚上8:14
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [amiralansary/rl-medical] how can I get the cardiac dataset in this project? (#23)





 
This is related to #22
 Unfortunately, the cardiac dataset used in this project is not publicly available. However, the code should be working on any other 3D medical data.

**Comment by hlyf-xs** [comment]
I have studied in this project, It's a good job! I found you remained some 2D parameters and annotations, so&nbsp;it seems to be also implemented on 2D medical images?






------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "amiralansary/rl-medical"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年3月15日(星期一) 晚上8:14
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [amiralansary/rl-medical] how can I get the cardiac dataset in this project? (#23)





 
This is related to #22
 Unfortunately, the cardiac dataset used in this project is not publicly available. However, the code should be working on any other 3D medical data.

**Comment by amiralansary** [comment]
The cardiac data were obtrained from our collaborators in the hospital. Regarding the 2D implmentation, it was work in progress that should be very similar to the 3D implementation. Please feel free to make a pull request if you modify or add any code for the 2D implmentation. Thanks!

**Comment by hlyf-xs** [comment]
OK,Thank you very much! I'll pull all my efforts to modify the project for the 2D implementation on cardiac images. Thanks again!


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "amiralansary/rl-medical"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年3月17日(星期三) 晚上7:13
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [amiralansary/rl-medical] how can I get the cardiac dataset in this project? (#23)





 
The cardiac data were obtrained from our collaborators in the hospital. Regarding the 2D implmentation, it was work in progress that should be very similar to the 3D implementation. Please feel free to make a pull request if you modify or add any code for the 2D implmentation. Thanks!

**Comment by hlyf-xs** [comment]
Hello, Can you share me only about 10 cardiac images? I want to comprare them to my own dataset. Thanks very much!




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "amiralansary/rl-medical"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年3月15日(星期一) 晚上8:14
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [amiralansary/rl-medical] how can I get the cardiac dataset in this project? (#23)





 
This is related to #22
 Unfortunately, the cardiac dataset used in this project is not publicly available. However, the code should be working on any other 3D medical data.

**Comment by amiralansary** [comment]
Unfortunately, the cardiac data is privately owned by the hospital, and we cannot share it.
