### ISSUE TITLE
References to AtariPlayer in expreplay.py

### ISSUE THREAD

**Issue by crypdick** [amiralansary/rl-medical#5]
In both expreplay.py files, there are references to AtariPlayer:

```
if __name__ == '__main__':
    from .atari import AtariPlayer
```

There's no atari module, though. I think these are just leftover from the [original tensorpack example](https://github.com/tensorpack/tensorpack/blob/b96cb78cf550cb7ee348398b127e9cf20e4133be/examples/DeepQNetwork/expreplay.py#L269-L270)

**Comment by amiralansary** [comment]
This is fixed now - thanks!
